# Generated by Django 5.1.5 on 2025-08-27 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Program name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text="Overview of the program's purpose")),
                ('national_alignment', models.TextField(blank=True, help_text='Link to NDPIII, Roadmap, or 4IR goals')),
                ('focus_areas', models.CharField(blank=True, help_text='Domains such as IoT, automation, renewable energy (comma-separated)', max_length=255)),
                ('phases', models.CharField(blank=True, help_text='E.g., Cross-Skilling, Collaboration, Prototyping (comma-separated)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
