# Generated by Django 5.2.5 on 2025-08-29 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "facility_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Facility name e.g. Innovation Hub, IoT Lab",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Overview of the facility and what it offers",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City/District or GPS coordinates",
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Type e.g. MakerSpace, Research Lab, University, Virtual Hub",
                        max_length=100,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Max number of people the facility can accommodate",
                        null=True,
                    ),
                ),
                (
                    "resources",
                    models.TextField(
                        blank=True,
                        help_text="Available equipment, tools, or services (comma-separated)",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, help_text="Facility contact email", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Facility contact phone", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "programs",
                    models.ManyToManyField(
                        blank=True, related_name="facilities", to="core.program"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
