# Generated by Django 5.2.5 on 2025-08-31 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('NatureOfProject', models.CharField(choices=[('research', 'Research'), ('prototype', 'Prototype'), ('applied', 'Applied Work')], max_length=20)),
                ('Description', models.TextField()),
                ('InnovationFocus', models.CharField(choices=[('iot', 'IoT Devices'), ('smart_home', 'Smart Home'), ('renewable_energy', 'Renewable Energy'), ('other', 'Other')], max_length=20)),
                ('PrototypeStage', models.CharField(choices=[('concept', 'Concept'), ('prototype', 'Prototype'), ('mvp', 'MVP'), ('market_launch', 'Market Launch')], max_length=20)),
                ('TestingRequirements', models.TextField()),
                ('CommercializationPlan', models.TextField()),
                ('FacilityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.facility')),
                ('ProgramId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.program')),
            ],
        ),
    ]
