# Generated by Django 5.2.5 on 2025-09-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('affiliation', models.CharField(choices=[('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('Engineering', 'Engineering'), ('Other', 'Other')], max_length=50)),
                ('specialization', models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Business', 'Business')], max_length=50)),
                ('cross_skill_trained', models.BooleanField(default=False)),
                ('institution', models.CharField(choices=[('SCIT', 'SCIT'), ('CEDAT', 'CEDAT'), ('UniPod', 'UniPod'), ('UIRI', 'UIRI'), ('Lwera', 'Lwera')], max_length=100)),
                ('role_on_project', models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Contributor', 'Contributor')], max_length=50)),
                ('skill_role', models.CharField(choices=[('Developer', 'Developer'), ('Engineer', 'Engineer'), ('Designer', 'Designer'), ('Business Lead', 'Business Lead')], max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.project')),
            ],
        ),
    ]
