# Generated by Django 5.2.5 on 2025-09-05 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('Outcomeld', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True)),
                ('ArtifactLink', models.URLField(blank=True, max_length=500)),
                ('OutcomeType', models.CharField(choices=[('CAD', 'CAD'), ('PCB', 'PCB'), ('Prototype', 'Prototype'), ('Report', 'Report'), ('Business Plan', 'Business Plan')], default='Report', max_length=20)),
                ('QualityCertification', models.CharField(blank=True, max_length=200)),
                ('CommercializationStatus', models.CharField(blank=True, choices=[('Demoed', 'Demoed'), ('Market Linked', 'Market Linked'), ('Launched', 'Launched')], max_length=20)),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='core.project')),
            ],
        ),
    ]
