# Generated by Django 5.2.5 on 2025-09-09 07:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='inventory_code',
            field=models.CharField(help_text="Tracking code (e.g., 'EQ-CNC-001', 'PRINTER-3D-A2')", max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Inventory code must contain only letters, numbers, hyphens, and underscores', regex='^[A-Za-z0-9\\-_]+$')]),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='ProjectId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='core.project'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='affiliation',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('Engineering', 'Engineering'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='institution',
            field=models.CharField(blank=True, choices=[('SCIT', 'SCIT'), ('CEDAT', 'CEDAT'), ('UniPod', 'UniPod'), ('UIRI', 'UIRI'), ('Lwera', 'Lwera')], max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.project'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role_on_project',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Contributor', 'Contributor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='skill_role',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Engineer', 'Engineer'), ('Designer', 'Designer'), ('Business Lead', 'Business Lead')], max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='specialization',
            field=models.CharField(blank=True, choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Business', 'Business')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='CommercializationPlan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='FacilityId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='project',
            name='InnovationFocus',
            field=models.CharField(blank=True, choices=[('iot', 'IoT Devices'), ('smart_home', 'Smart Home'), ('renewable_energy', 'Renewable Energy'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='NatureOfProject',
            field=models.CharField(blank=True, choices=[('research', 'Research'), ('prototype', 'Prototype'), ('applied', 'Applied Work')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProgramId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.program'),
        ),
        migrations.AlterField(
            model_name='project',
            name='PrototypeStage',
            field=models.CharField(blank=True, choices=[('concept', 'Concept'), ('prototype', 'Prototype'), ('mvp', 'MVP'), ('market_launch', 'Market Launch')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='TestingRequirements',
            field=models.TextField(blank=True),
        ),
    ]
